name: labgrid-playground
services:
  crossbar:
    build:
      context: ./crossbar
    command: "bash -c \"crossbar init && jq '.workers[0].realms[0].roles[0].permissions[0].disclose = {caller: true, publisher: true}' .crossbar/config.json | sponge .crossbar/config.json && crossbar start\""
    healthcheck:
      test: curl --fail http://127.0.0.1:8080
      interval: 10s
  coordinator:
    build:
      context: ./labgrid
    command: python3 -m labgrid.remote.coordinator
    environment:
      WS: ws://crossbar:8080/ws
    depends_on:
      crossbar:
        condition: service_healthy
  exporter:
    build:
      context: ./labgrid
    command: labgrid-exporter /exporter/configuration.yaml
    environment:
      LG_CROSSBAR: ws://crossbar:8080/ws
    volumes:
      - ./exporter:/exporter
    depends_on:
      crossbar:
        condition: service_healthy
  client:
    build:
      context: ./labgrid
    command: bash
    tty: true
    environment:
      LG_CROSSBAR: ws://crossbar:8080/ws
    depends_on:
      crossbar:
        condition: service_healthy
